name: Build and Release Helm charts (OCI -> GHCR)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
      type:
        description: 'Name of the software that should be released.'
        required: true
        type: choice
        options:
          - stunner
          - stunner-premium
          - stunner-prometheus
      ref:
        description: 'Branch / tag / SHA to build from'
        required: false
        default: 'main'

env:
  TAG: ${{ inputs.tag }}
  TYPE: ${{ inputs.type }}
  REF: ${{ inputs.ref }}
  OWNER: ${{ github.repository_owner }}
  OCI_REPO: charts

permissions:
  contents: read
  packages: write

jobs:
  push_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Log inputs
        run: |
          echo "Version is $TAG"
          echo "Triggered by $TYPE"
          echo "Ref is $REF"

      - name: Checkout repository at requested ref
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}
          fetch-depth: 0

      - name: Edit helm chart for stunner (stunner-gateway-operator previously)
        if: ${{ env.TYPE == 'stunner' }}
        run: |
          cd helm
          if ${{ env.TAG == 'dev' }}; then
            sed -ri 's/^(\s*)(name\s*:\s*.*\s*$)/\1name: stunner-gateway-operator-dev/' stunner-gateway-operator/Chart.yaml
            sed -i '/stunnerGatewayOperator:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
            sed -i '/dataplane:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
            sed -i '/authService:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
          else
            sed -ri 's/^(\s*)(version\s*:\s*.*\s*$)/\1version: ${{ env.TAG }}/' stunner-gateway-operator/Chart.yaml
          fi
          sed -i '/stunnerGatewayOperator:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -i '/dataplane:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -i '/authService:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -ri 's/^(\s*)(appVersion\s*:\s*.*\s*$)/\1appVersion: ${{ env.TAG }}/' stunner-gateway-operator/Chart.yaml

      - name: Edit helm chart for stunner-premium
        if: ${{ env.TYPE == 'stunner-premium' }}
        run: |
          cd helm
          if ${{ env.TAG == 'dev' }}; then
            sed -ri 's/^(\s*)(name\s*:\s*.*\s*$)/\1name: stunner-gateway-operator-dev/' stunner-gateway-operator/Chart.yaml
            sed -i '/stunnerGatewayOperator:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
            sed -i '/dataplane:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
            sed -i '/authService:/,/pullPolicy:/ s/\(pullPolicy:\s*\).*/\1Always/' stunner-gateway-operator/values.yaml
          else
            sed -ri 's/^(\s*)(version\s*:\s*.*\s*$)/\1version: ${{ env.TAG }}/' stunner-gateway-operator/Chart.yaml
          fi
          sed -i '/stunnerGatewayOperator:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -i '/dataplane:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -i '/authService:/,/tag:/ s/\(tag:\s*\).*/\1'"${{ env.TAG }}"'/' stunner-gateway-operator/values.yaml
          sed -ri 's/^(\s*)(appVersion\s*:\s*.*\s*$)/\1appVersion: ${{ env.TAG }}/' stunner-gateway-operator/Chart.yaml
          sed -i '/container:/,/name:/ s/\(name:\s*\)docker\.io\/l7mp\/stunner-gateway-operator/\1docker.io\/l7mp\/stunner-gateway-operator-premium/' stunner-gateway-operator/values.yaml
          sed -i '/dataplane:/,/name:/ s/\(name:\s*\)docker\.io\/l7mp\/stunnerd/\1docker.io\/l7mp\/stunnerd-premium/' stunner-gateway-operator/values.yaml
          sed -ri 's/^(\s*)(name\s*:\s*.*\s*$)/\1name: stunner-premium/' stunner-gateway-operator/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: |
          ct lint --all --chart-dirs helm --excluded-charts stunner-kurento-one2one-call

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        run: |
          if ${{ env.TYPE == 'stunner-prometheus' }}; then
            ct install --chart-dirs helm --charts helm/stunner-prometheus
          else
            ct install --chart-dirs helm --charts helm/stunner-gateway-operator
          fi

      - name: Build helm chart for ${{ env.TYPE }}
        run: |
          cd helm
          if ${{ env.TYPE == 'stunner-prometheus' }}; then
            helm package stunner-prometheus
          else
            helm package stunner-gateway-operator
          fi
          ls -lah *.tgz

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Helm chart to GHCR (OCI)
        run: |
          cd helm
          CHART_TGZ="$(ls -1 *.tgz | head -n 1)"
          echo "Pushing $CHART_TGZ to oci://ghcr.io/${{ env.OWNER }}/${{ env.OCI_REPO }}"
          helm push "$CHART_TGZ" "oci://ghcr.io/${{ env.OWNER }}/${{ env.OCI_REPO }}"
